# Origin entity
mars_topology_msgs/TopologyEntity origin
# Destination entity
mars_topology_msgs/TopologyEntity destination
# Coordinate of the origin entity
geometry_msgs/PointStamped origin_location
# Coordinate of the destination entity
geometry_msgs/PointStamped destination_location
# Planned time interval for traversing to the destination
mars_topology_msgs/TimeInterval time_interval
# Planned time profile 
mars_routing_msgs/TimeProfile time_profile
