# Id of the agent which needs the reservation
mars_common_msgs/Id agent_id
# Id of the entity
mars_common_msgs/Id entity_id
# Id of the path
mars_common_msgs/Id path_id
# Timeinteral of the reservation
mars_topology_msgs/TimeInterval time_interval
# timestamp allocation request
time allocation_request
#timestamp successful allocation
time allocation_successful
#timestamp deallocation
time deallocation
