# supported topology entity types
uint8 TOPOLOGY_ENTITY_TYPE_UNKNOWN=0

# Topology vertex types:
# TODO: add needed topology vertex types
uint8 TOPOLOGY_VERTEX_TYPE_WAYPOINT=10
uint8 TOPOLOGY_VERTEX_TYPE_PICKING_STATION=11
uint8 TOPOLOGY_VERTEX_TYPE_PARKING_LOT=20

uint8 TOPOLOGY_VERTEX_TYPE_MIN=10
uint8 TOPOLOGY_VERTEX_TYPE_MAX=99

# Topology edge types:
# TODO: add needed topology edge types
uint8 TOPOLOGY_EDGE_TYPE_EDGE=100

uint8 TOPOLOGY_EDGE_TYPE_MIN=100
uint8 TOPOLOGY_EDGE_TYPE_MAX=199

uint8 entity_type
