# Supported value_types
string VALUE_TYPE_BOOL=bool
string VALUE_TYPE_INT8=int8
string VALUE_TYPE_UINT8=uint8
string VALUE_TYPE_INT16=int16
string VALUE_TYPE_UINT16=uint16
string VALUE_TYPE_INT32=int32
string VALUE_TYPE_UINT32=uint32
string VALUE_TYPE_INT64=int64
string VALUE_TYPE_UINT64=uint64
string VALUE_TYPE_FLOAT32=float32
string VALUE_TYPE_FLOAT64=float64
string VALUE_TYPE_STRING=string

# type description of the value
string value_type
# value of type "value_type"
string value
